# -*- coding: utf-8 -*-
"""even odd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def check_even_odd(num):
    if num % 2 == 0:
        print("The number is Even")
    else:
        print("The number is Odd")

# taking input from user
n = int(input("Enter a number: "))

check_even_odd(n)