# -*- coding: utf-8 -*-
"""prime number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def check_prime(num):
    if num <= 1:
        print("Not a Prime number")
        return

    for i in range(2, num):
        if num % i == 0:
            print("Not a Prime number")
            return

    print("Prime number")

# taking input
n = int(input("Enter a number: "))

check_prime(n)