# -*- coding: utf-8 -*-
"""string reverse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def reverse_string(s):
    return s[::-1]

text = "hello world"
print(reverse_string(text))