# -*- coding: utf-8 -*-
"""tuple reverse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def reverse_tuple(t):
    return t[::-1]

t = (1, 2, 3, 4)

print(reverse_tuple(t))