# -*- coding: utf-8 -*-
"""vowel check.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def check_vowel(ch):
    if ch.lower() in 'aeiou':
        print("It is a Vowel")
    else:
        print("It is not a Vowel")

# taking input from user
c = input("Enter a character: ")

check_vowel(c)